// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachersBack2.Data;

#nullable disable

namespace TeachersBack2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107054208_Add_dayOfWeek_toHistory")]
    partial class Add_dayOfWeek_toHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeachersBack2.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("TeachersBack2.Models.Center", b =>
                {
                    b.Property<string>("CenterCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CenterCode");

                    b.ToTable("Centers");

                    b.HasData(
                        new
                        {
                            CenterCode = "1",
                            Title = "ستاد استان"
                        },
                        new
                        {
                            CenterCode = "6293",
                            Title = "مركز شیراز"
                        },
                        new
                        {
                            CenterCode = "6317",
                            Title = "مركز استهبان"
                        },
                        new
                        {
                            CenterCode = "1910",
                            Title = "مركز اوز"
                        },
                        new
                        {
                            CenterCode = "1032",
                            Title = "مركز آباده"
                        },
                        new
                        {
                            CenterCode = "1049",
                            Title = "مركز بوانات"
                        },
                        new
                        {
                            CenterCode = "3974",
                            Title = "مركز جهرم"
                        },
                        new
                        {
                            CenterCode = "4106",
                            Title = "مركز خرامه"
                        },
                        new
                        {
                            CenterCode = "4533",
                            Title = "مركز داراب"
                        },
                        new
                        {
                            CenterCode = "1061",
                            Title = "مركز صفاشهر"
                        },
                        new
                        {
                            CenterCode = "3997",
                            Title = "مركز فسا"
                        },
                        new
                        {
                            CenterCode = "6811",
                            Title = "مركز فیروزآباد"
                        },
                        new
                        {
                            CenterCode = "9116",
                            Title = "مركز كازرون"
                        },
                        new
                        {
                            CenterCode = "8054",
                            Title = "مركز لامرد"
                        },
                        new
                        {
                            CenterCode = "9092",
                            Title = "مركز نور آبادممسنی"
                        },
                        new
                        {
                            CenterCode = "2825",
                            Title = "واحد ارسنجان"
                        },
                        new
                        {
                            CenterCode = "2848",
                            Title = "واحد اقلید"
                        },
                        new
                        {
                            CenterCode = "2854",
                            Title = "واحد بیضا"
                        },
                        new
                        {
                            CenterCode = "2877",
                            Title = "واحد خاوران"
                        },
                        new
                        {
                            CenterCode = "29",
                            Title = "واحد رستم"
                        },
                        new
                        {
                            CenterCode = "28",
                            Title = "واحد زرقان"
                        },
                        new
                        {
                            CenterCode = "52",
                            Title = "واحد زرین دشت"
                        },
                        new
                        {
                            CenterCode = "5764",
                            Title = "واحد سپیدان"
                        },
                        new
                        {
                            CenterCode = "6323",
                            Title = "واحد سروستان"
                        },
                        new
                        {
                            CenterCode = "2907",
                            Title = "واحد فراشبند"
                        },
                        new
                        {
                            CenterCode = "5846",
                            Title = "واحد قیروكارزین"
                        },
                        new
                        {
                            CenterCode = "5800",
                            Title = "واحد كوار"
                        },
                        new
                        {
                            CenterCode = "2913",
                            Title = "واحد لار"
                        },
                        new
                        {
                            CenterCode = "6300",
                            Title = "واحد مرودشت"
                        },
                        new
                        {
                            CenterCode = "41",
                            Title = "واحد نودان"
                        },
                        new
                        {
                            CenterCode = "4541",
                            Title = "واحد نی ریز"
                        },
                        new
                        {
                            CenterCode = "2819",
                            Title = "واحد آباده طشك"
                        },
                        new
                        {
                            CenterCode = "2883",
                            Title = "واحد خنج"
                        },
                        new
                        {
                            CenterCode = "5817",
                            Title = "واحد مهر"
                        });
                });

            modelBuilder.Entity("TeachersBack2.Models.ChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangeHistory");
                });

            modelBuilder.Entity("TeachersBack2.Models.ComponentFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "کامپوننت شماره صندلی امتحانات پایان ترم دانشجو",
                            IsActive = false,
                            Name = "ExamSeat"
                        });
                });

            modelBuilder.Entity("TeachersBack2.Models.ExamSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classroom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Row")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShSh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamSeats");
                });

            modelBuilder.Entity("TeachersBack2.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ادمین سایت",
                            Title = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ادمین مرکز",
                            Title = "centerAdmin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "برنامه ریزی",
                            Title = "programmer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "استاد",
                            Title = "teacher"
                        });
                });

            modelBuilder.Entity("TeachersBack2.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Center")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CooperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutivePosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TeachersBack2.Models.TeacherTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNeighborTeaching")
                        .HasColumnType("bit");

                    b.Property<string>("NeighborCenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeighborTeaching")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Projector")
                        .HasColumnType("bit");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Whiteboard2")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TeacherTerms");
                });

            modelBuilder.Entity("TeachersBack2.Models.TermCalender", b =>
                {
                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Term");

                    b.ToTable("TermCalenders");
                });

            modelBuilder.Entity("TeachersBack2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NationalCode")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenterCode = "1",
                            Email = "admin@example.com",
                            FirstName = "ادمین",
                            IsActive = true,
                            LastName = "ادمین",
                            Mobile = "09120000000",
                            NationalCode = "0000000000",
                            PasswordHash = "$2a$12$BhFI37anzgtbV2200UY1DO6VR2WKEOvyuZngKhhMknmIxmND12b5C",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TeachersBack2.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("TeachersBack2.Models.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternativeHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Center")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForbiddenHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeeklySchedules");
                });

            modelBuilder.Entity("TeachersBack2.Models.UserRole", b =>
                {
                    b.HasOne("TeachersBack2.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachersBack2.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachersBack2.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TeachersBack2.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
